### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by taveratch** [masty123/stopwatch#3]
Remove some useless blank lines.

Put a blank line between each method. (Check the other files too)
https://github.com/masty123/stopwatch/blob/master/src/Stopwatch/Stopwatch.java#L9-L10

As you can see, this code is rather hard to read. (Please re-arrange them)

```java
public boolean isRunning()
    {
    	return isStart;
    }
    /**@return the durtion of stopwatch in seconds*/

    /**Start the stopwatch.*/
	public void start() 
	{
		
		if (!isStart) 
		{
			isStart = true ;
			startTime = System.nanoTime();	
		} 
	}
```

**Comment by masty123** [comment]
fixed it
